# Generated by Django 5.1.7 on 2025-03-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=100)),
                ('sortable_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('children', models.JSONField()),
                ('cfr_references', models.JSONField()),
            ],
        ),
    ]
