# Generated by Django 5.1.7 on 2025-03-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agency_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='cfr_references',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('chapter', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='agency',
            name='cfr_references',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cfr_references'),
        ),
        migrations.CreateModel(
            name='ChildAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=100)),
                ('sortable_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('cfr_references', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cfr_references')),
            ],
        ),
        migrations.AlterField(
            model_name='agency',
            name='children',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.childagency'),
        ),
    ]
