# Generated by Django 5.1.7 on 2025-03-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cfr_references_alter_agency_cfr_references_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cfr_references',
            new_name='CfrReferences',
        ),
    ]
