# Generated by Django 5.1.7 on 2025-03-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cfr_reference_alter_agency_cfr_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfr_reference',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
