# Generated by Django 5.1.7 on 2025-03-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cfr_reference_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfr_reference',
            name='chapter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
