# Generated by Django 5.1.7 on 2025-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cfr_reference_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childagency',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
