# Generated by Django 5.1.7 on 2025-03-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_childagency_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childagency',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childagency',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childagency',
            name='sortable_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
