# Generated by Django 5.1.7 on 2025-03-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_childagency_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childagency',
            name='cfr_reference',
        ),
        migrations.AlterField(
            model_name='agency',
            name='cfr_references',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='agency',
            name='children',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='cfr_reference',
        ),
        migrations.DeleteModel(
            name='ChildAgency',
        ),
    ]
