# Generated by Django 5.1.7 on 2025-03-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_childagency_cfr_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfrReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agency',
            name='children',
        ),
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.agency'),
        ),
        migrations.RemoveField(
            model_name='agency',
            name='cfr_references',
        ),
        migrations.AddField(
            model_name='agency',
            name='cfr_references',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='app.cfrreference'),
        ),
    ]
