# Generated by Django 5.1.7 on 2025-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cfrreference_remove_agency_children_agency_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfrreference',
            name='chapter_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cfrreference',
            name='title_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
