# Generated by Django 5.1.7 on 2025-03-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cfrreference_chapter_size_cfrreference_title_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfrreference',
            name='chapter_size',
        ),
        migrations.RemoveField(
            model_name='cfrreference',
            name='title_size',
        ),
    ]
